require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 25
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/CaseIndentation:
  EnforcedStyle: end
Metrics/BlockLength:
  Max: 40
