# This file's purpose is to outline all of the various config settings this library includes.

# The different environments have their own file in the environments/ folder.

# When adding a new setting, please ensure this file is updated.
# Additionally, ensure all settings are sorted alphabetically.
---
# Do you want output text displayed when performing various methods
colour_output:  # bool
display_output: # bool

runescape_urls:
  hiscore_url: 'https://secure.runescape.com/m=hiscore/index_lite.ws?'
  monthly_xp_url: 'https://apps.runescape.com/runemetrics/xp-monthly'
  unavailable_url: 'https://www.runescape.com/unavailable'
