# When adding a new setting, please ensure this file is updated.
# Additionally, ensure all settings are sorted alphabetically.

---
colour_output: true
display_output: true

google_credential_path: <%= ENV.fetch('RS_API_GOOGLE_CRED') %>
