# When adding a new setting, please ensure this file is updated.
# Additionally, ensure all settings are sorted alphabetically.

---
colour_output: false
display_output: false

google_credential_path: 'dummy'
